module.exports = {
	LOGIN: 'LOGIN',
	LOGOUT: 'LOGOUT',
	GET_USERS: 'GET_USERS',
	SET_USER: 'SET_USER',
	UPDATE_USER: 'UPDATE_USER',
	GET_SESSIONS: 'GET_SESSIONS',
	GET_USER_SESSIONS: 'GET_USER_SESSIONS',
	GET_FREE_SESSIONS: 'GET_FREE_SESSIONS',
	GET_BUSY_SESSIONS: 'GET_BUSY_SESSIONS',
	GET_ERROR_SESSIONS: 'GET_ERROR_SESSIONS',
	GET_SUCCESS_SESSIONS: 'GET_SUCCESS_SESSIONS',
	GET_ACTIVE_SESSIONS: 'GET_ACTIVE_SESSIONS',
	GET_INACTIVE_SESSIONS: 'GET_INACTIVE_SESSIONS'
}